# Generated by Django 3.2.1 on 2021-05-04 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_state', models.IntegerField(choices=[(1, 'None'), (2, 'Player'), (3, 'Computer'), (4, 'Tie')], default=1)),
                ('game_state', models.IntegerField(choices=[(1, 'Not Started'), (2, 'Ongoing'), (3, 'Finished')], default=1)),
                ('board_state', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
