# Generated by Django 3.2.1 on 2021-05-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('winner_state', models.IntegerField(choices=[(1, 'None'), (2, 'Player'), (3, 'Computer'), (4, 'Tie')], default=1)),
                ('game_state', models.IntegerField(choices=[(1, 'Not Started'), (2, 'Ongoing'), (3, 'Finished')], default=1)),
                ('board_state', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
